// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: calculator/v1/calculator.proto

package calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float32                `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float32                `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetA() float32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddRequest) GetB() float32 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type SubtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float32                `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float32                `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtractRequest) Reset() {
	*x = SubtractRequest{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractRequest) ProtoMessage() {}

func (x *SubtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractRequest.ProtoReflect.Descriptor instead.
func (*SubtractRequest) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *SubtractRequest) GetA() float32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *SubtractRequest) GetB() float32 {
	if x != nil {
		return x.B
	}
	return 0
}

type SubtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtractResponse) Reset() {
	*x = SubtractResponse{}
	mi := &file_calculator_v1_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractResponse) ProtoMessage() {}

func (x *SubtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_v1_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractResponse.ProtoReflect.Descriptor instead.
func (*SubtractResponse) Descriptor() ([]byte, []int) {
	return file_calculator_v1_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *SubtractResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calculator_v1_calculator_proto protoreflect.FileDescriptor

const file_calculator_v1_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1ecalculator/v1/calculator.proto\x12\rcalculator.v1\"(\n" +
	"\n" +
	"AddRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x02R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x02R\x01b\"%\n" +
	"\vAddResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\"-\n" +
	"\x0fSubtractRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x02R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x02R\x01b\"*\n" +
	"\x10SubtractResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result2\xa2\x01\n" +
	"\x11CalculatorService\x12>\n" +
	"\x03Add\x12\x19.calculator.v1.AddRequest\x1a\x1a.calculator.v1.AddResponse\"\x00\x12M\n" +
	"\bSubtract\x12\x1e.calculator.v1.SubtractRequest\x1a\x1f.calculator.v1.SubtractResponse\"\x00B\xac\x01\n" +
	"\x11com.calculator.v1B\x0fCalculatorProtoP\x01Z1calculator-demo/internal/calculator/v1;calculator\xa2\x02\x03CXX\xaa\x02\rCalculator.V1\xca\x02\rCalculator\\V1\xe2\x02\x19Calculator\\V1\\GPBMetadata\xea\x02\x0eCalculator::V1b\x06proto3"

var (
	file_calculator_v1_calculator_proto_rawDescOnce sync.Once
	file_calculator_v1_calculator_proto_rawDescData []byte
)

func file_calculator_v1_calculator_proto_rawDescGZIP() []byte {
	file_calculator_v1_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_v1_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_v1_calculator_proto_rawDesc), len(file_calculator_v1_calculator_proto_rawDesc)))
	})
	return file_calculator_v1_calculator_proto_rawDescData
}

var file_calculator_v1_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calculator_v1_calculator_proto_goTypes = []any{
	(*AddRequest)(nil),       // 0: calculator.v1.AddRequest
	(*AddResponse)(nil),      // 1: calculator.v1.AddResponse
	(*SubtractRequest)(nil),  // 2: calculator.v1.SubtractRequest
	(*SubtractResponse)(nil), // 3: calculator.v1.SubtractResponse
}
var file_calculator_v1_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.v1.CalculatorService.Add:input_type -> calculator.v1.AddRequest
	2, // 1: calculator.v1.CalculatorService.Subtract:input_type -> calculator.v1.SubtractRequest
	1, // 2: calculator.v1.CalculatorService.Add:output_type -> calculator.v1.AddResponse
	3, // 3: calculator.v1.CalculatorService.Subtract:output_type -> calculator.v1.SubtractResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_v1_calculator_proto_init() }
func file_calculator_v1_calculator_proto_init() {
	if File_calculator_v1_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_v1_calculator_proto_rawDesc), len(file_calculator_v1_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_v1_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_v1_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_v1_calculator_proto_msgTypes,
	}.Build()
	File_calculator_v1_calculator_proto = out.File
	file_calculator_v1_calculator_proto_goTypes = nil
	file_calculator_v1_calculator_proto_depIdxs = nil
}
