services:
  calculator-service:
    image: calculator-service
    build:
      context: ./calculator
      dockerfile: Dockerfile.service
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-service.env
    networks:
      - grpc-gateway-demo

  calculator-gateway-1:
    image: calculator-gateway
    build:
      context: ./calculator
      dockerfile: Dockerfile.gateway
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-gateway.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - calculator-service

  calculator-gateway-2:
    image: calculator-gateway
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-gateway.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - calculator-service

  calculator-pipeline-http-request-1:
    image: calculator-pipeline-http-request
    build: ./calculator/pipelines/http_request
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-pipeline.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - calculator-gateway-1
      - calculator-gateway-2

  calculator-pipeline-http-request-2:
    image: calculator-pipeline-http-request
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-pipeline.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - calculator-gateway-1
      - calculator-gateway-2

  calculator-pipeline-cron-request:
    image: calculator-pipeline-cron-request
    build: ./calculator/pipelines/cron_request
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-pipeline.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - calculator-gateway-1
      - calculator-gateway-2

  calculator-pipeline-nats-request:
    image: calculator-pipeline-nats-request
    build: ./calculator/pipelines/nats_request
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-pipeline.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - nats
      - calculator-gateway-1
      - calculator-gateway-2

  httpbin:
    image: mccutchen/go-httpbin
    restart: unless-stopped
    networks:
      - grpc-gateway-demo

  nats:
    image: nats
    restart: unless-stopped
    ports:
      - "4222:4222"
    networks:
      - grpc-gateway-demo

  postgres:
    image: postgres
    build: ./infra/postgres
    restart: unless-stopped
    env_file:
      - ./infra/env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - grpc-gateway-demo

  prometheus:
    image: prometheus
    build: ./infra/prometheus
    restart: unless-stopped
    volumes:
      - prometheus:/prometheus
    networks:
      - grpc-gateway-demo

  grafana:
    image: grafana
    build: ./infra/grafana
    restart: unless-stopped
    env_file:
      - ./infra/env/grafana.env
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - grpc-gateway-demo
    depends_on:
      - postgres
      - prometheus

  # Uncomment to enable prometheus remote write:
  # alloy:
  #   image: alloy
  #   build: ./infra/alloy
  #   restart: unless-stopped
  #   env_file:
  #     - ./infra/env/alloy.env
  #   volumes:
  #     - alloy:/var/lib/alloy/data
  #   networks:
  #     - grpc-gateway-demo

  caddy:
    image: caddy
    build: ./infra/caddy
    restart: unless-stopped
    env_file:
      - ./infra/env/caddy.env
    ports:
      - "8000:8080"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      grpc-gateway-demo:
        aliases:
          - calculator-gateway

networks:
  grpc-gateway-demo:
    name: grpc-gateway-demo

volumes:
  postgres:
  prometheus:
  grafana:
  # Uncomment to enable prometheus remote write:
  # alloy:
  caddy_data:
  caddy_config:
