services:
  calculator-service:
    image: calculator-service
    build:
      context: ./calculator
      dockerfile: Dockerfile.service
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-service.env
    networks:
      - grpc-gateway-demo

  calculator-gateway-1:
    image: calculator-gateway
    build:
      context: ./calculator
      dockerfile: Dockerfile.gateway
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-gateway.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - calculator-service

  calculator-gateway-2:
    image: calculator-gateway
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-gateway.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - calculator-service

  calculator-pipeline-1:
    image: calculator-pipeline
    build: ./calculator/pipeline
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-pipeline.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - calculator-gateway-1
      - calculator-gateway-2

  calculator-pipeline-2:
    image: calculator-pipeline
    restart: unless-stopped
    env_file:
      - ./calculator/env/calculator-pipeline.env
    networks:
      - grpc-gateway-demo
    depends_on:
      - calculator-gateway-1
      - calculator-gateway-2

  postgres:
    image: postgres
    build: ./infra/postgres
    restart: unless-stopped
    env_file:
      - ./infra/env/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - grpc-gateway-demo

  prometheus:
    image: prometheus
    build: ./infra/prometheus
    restart: unless-stopped
    volumes:
      - prometheus:/prometheus
    networks:
      - grpc-gateway-demo

  grafana:
    image: grafana
    build: ./infra/grafana
    restart: unless-stopped
    env_file:
      - ./infra/env/grafana.env
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - grpc-gateway-demo
    depends_on:
      - postgres
      - prometheus

  proxy:
    image: proxy
    build: ./infra/proxy
    restart: unless-stopped
    env_file:
      - ./infra/env/proxy.env
    ports:
      - "8000:8080"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      grpc-gateway-demo:
        aliases:
          - calculator-gateway

networks:
  grpc-gateway-demo:
    name: grpc-gateway-demo

volumes:
  caddy_data:
  caddy_config:
  postgres:
  prometheus:
  grafana:
