input:
  generate:
    mapping: root = {}
    interval: 0/10 * * * * *

pipeline:
  threads: 1
  processors:
    - try:
        - mapping: |
            root = file_rel("config.json").parse_json().calculations

        - unarchive:
            format: json_array

        - branch:
            request_map: |
              meta calculator_operation = this.operation
              root.a = this.a
              root.b = this.b
            processors:
              - http:
                  url: ${CALCULATOR_GATEWAY_ADDRESS}/v1/calculator/${!@calculator_operation}
                  verb: POST
                  headers:
                    Api-Key: ${CALCULATOR_GATEWAY_API_KEY}
                    Content-Type: application/json
            result_map: |
              root.result = this.result

        - branch:
            request_map: root = this
            processors:
              - http:
                  url: ${HTTPBIN_ADDRESS}/unstable?failure_rate=0.1
                  verb: POST
                  headers:
                    Content-Type: application/json
                  retries: 0

    - mapping: |
        if errored() {
          root.error.code = 500
          root.error.message = error()
        } else {
          root.result = this.result
        }
        root.processed_on = hostname()
        root.processed_at = now()
        root.processed_by = "calculator-pipeline-cron-request"

output:
  switch:
    cases:
      - check: errored()
        output:
          sql_raw:
            driver: postgres
            dsn: ${POSTGRES_CONNECTIONSTRING}
            query: INSERT INTO demo.error_requests (error_message, data) VALUES ($1, $2);
            args_mapping: root = [error(), content()]

      - output:
          sql_raw:
            driver: postgres
            dsn: ${POSTGRES_CONNECTIONSTRING}
            query: INSERT INTO demo.success_requests (data) VALUES ($1);
            args_mapping: root = [content()]

http:
  address: ${HTTP_ADDRESS}

logger:
  level: ${LOG_LEVEL:INFO}
  format: logfmt
  static_fields:
    service: calculator-pipeline-cron-request

tracer:
  open_telemetry_collector:
    grpc:
      - address: ${OPEN_TELEMETRY_COLLECTOR_GRPC_ADDRESS}

shutdown_delay: 5s
