FROM golang AS build
COPY . .
ENV GOPATH=""
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
RUN go build -trimpath -a -ldflags="-w -s" ./cmd/calculator-service

FROM gcr.io/distroless/static
COPY --from=build /go/calculator-service /calculator-service
ENTRYPOINT ["/calculator-service"]
