type: google.api.Service
config_version: 3

http:
  rules:
    - selector: calculator.v1.CalculatorService.Add
      post: /v1/calculator/add
      body: "*"

    - selector: calculator.v1.CalculatorService.Subtract
      post: /v1/calculator/subtract
      body: "*"
